# Generated by Django 2.2.1 on 2019-12-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100)),
                ('tdata', models.CharField(max_length=100)),
                ('tno', models.CharField(max_length=100)),
                ('startCity', models.CharField(max_length=100)),
                ('startTime', models.CharField(max_length=100)),
                ('arrCity', models.CharField(max_length=100)),
                ('arrTime', models.CharField(max_length=100)),
                ('seatSum', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tdata', models.CharField(max_length=100)),
                ('tno', models.CharField(max_length=100)),
                ('startCity', models.CharField(max_length=100)),
                ('arrCity', models.CharField(max_length=100)),
                ('startTime', models.CharField(max_length=100)),
                ('arrTime', models.CharField(max_length=100)),
                ('seatSum', models.BigIntegerField()),
                ('ticketStill', models.BigIntegerField()),
                ('ticketBuy', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ismanage', models.CharField(max_length=100)),
                ('uname', models.CharField(max_length=100)),
                ('rname', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=20)),
                ('identity', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
